Repository wpninjas/ninja-forms, pull requests merged in 2018-05, with the labels that each got.

#3515 added way to validate data field before submit
  assets/js/front-end/controllers/changeDate.js
  assets/js/front-end/controllers/loadControllers.js
  assets/js/min/front-end--datepicker.min.js
  assets/js/min/front-end--rte.min.js
  assets/js/min/front-end.js
  assets/js/min/front-end.js.map
  includes/Config/FormDisplaySettings.php
  includes/Config/i18nFrontEnd.php
  includes/Display/Render.php
Labels: In Progress

#3518 fix php notice on form export
  includes/Database/Models/Form.php
Labels: In Progress

#3522 Plain Text Email Conversion
  includes/Database/Models/Form.php
Labels: In Progress, Needs Review, UPGRADE to THREE

#3520 Remove PHP Warning on Collect Payment
  assets/js/builder/controllers/actions/collectPayment.js
  assets/js/min/builder.js
  assets/js/min/builder.js.map
  includes/Actions/CollectPayment.php
Labels: Needs Review

#3528 Added telemetry for collation
  ninja-forms.php
Labels: In Progress, Needs Review

#3534 Removed unnecessary function that always returned true. Updated addon…
  deprecated/includes/admin/notices.php
  deprecated/ninja-forms.php
  deprecated/upgrade/class-submenu.php
Labels: Needs Review, UPGRADE to THREE

#3543 Issue#3530
  includes/Admin/Menus/Submissions.php
Labels: In Progress

#3559 Gdpr data request data removal
  assets/css/dashboard.min.css
  assets/css/dashboard.min.css.map
  assets/js/min/front-end.js
  assets/js/min/front-end.js.map
  assets/scss/dashboard/widgets/forms.scss
  includes/Actions/DeleteDataRequest.php
  includes/Actions/ExportDataRequest.php
  includes/Admin/UserDataRequests.php
  includes/Config/ActionDeleteDataRequestSettings.php
  includes/Config/ActionExportDataRequestSettings.php
  includes/Config/NewFormTemplates.php
  includes/Templates/formtemplate-deletedata.nff
  includes/Templates/formtemplate-exportdata.nff
  ninja-forms.php
Labels: In Progress

#3562 Gdpr optin
  assets/js/admin-settings.js
  assets/js/min/dashboard.min.js
  assets/js/min/dashboard.min.js.map
  client/dashboard/views/dashboardView.js
  deprecated/upgrade/class-submenu.php
  deprecated/upgrade/tmpl-submenu.html.php
  deprecated/upgrade/upgrade.js
  includes/Admin/Menus/Forms.php
  includes/Admin/Menus/Settings.php
  includes/Config/PluginSettingsAdvanced.php
  includes/Config/i18nDashboard.php
  includes/Dispatcher.php
  lib/NF_Tracking.php
Labels: In Progress, Needs Review

#3573 Gdpr exists
  ninja-forms.php
Labels: In Progress

#3561 changed has_archive to false to avoid an archive page with submissions
  includes/Admin/CPT/Submission.php
Labels: In Progress

#3574 fixes error on data export
  includes/Admin/UserDataRequests.php
Labels: In Progress

#3581 Redact removed values instead of leaving them blank.
  includes/Actions/Save.php
  includes/Fields/ListMultiSelect.php
Labels: In Progress, Needs Review

#3582 Remove nonsaving fields
  assets/css/builder.css.map
  assets/css/dashboard.min.css.map
  assets/css/display-opinions-dark.css.map
  assets/css/display-opinions-light.css.map
  assets/css/display-opinions.css.map
  assets/css/display-structure.css.map
  assets/js/builder/views/app/drawer/optionRepeaterOption.js
  assets/js/min/builder.js
  assets/js/min/builder.js.map
  includes/Actions/Save.php
  includes/Templates/admin-menu-new-form.html.php
Labels: In Progress

#3399 Ninja Forms Services
  assets/css/dashboard.min.css
  assets/css/dashboard.min.css.map
  assets/js/min/dashboard.min.js
  assets/js/min/dashboard.min.js.map
  assets/scss/dashboard/dashboard.scss
  assets/scss/dashboard/notices/oauth.scss
  assets/scss/dashboard/sections/promotions.scss
  assets/scss/dashboard/sections/services.scss
  client/dashboard/controllers/oauthController.js
  client/dashboard/controllers/servicesController.js
  client/dashboard/main.js
  client/dashboard/models/oauthModel.js
  client/dashboard/models/promotionModel.js
  client/dashboard/models/serviceCollection.js
  client/dashboard/models/serviceModel.js
  client/dashboard/views/dashboardView.js
  client/dashboard/views/oauth.js
  client/dashboard/views/promotion.js
  client/dashboard/views/sections/services.js
  client/dashboard/views/services/service.js
  client/dashboard/views/services/services.js
  includes/Actions/Email.php
  includes/Admin/Menus/Forms.php
  includes/Config/DashboardMenuItems.php
  includes/Config/DashboardPromotions.php
  includes/Templates/admin-menu-dashboard.html.php
  ninja-forms.php
  services/README.md
  services/bootstrap.php
  services/oauth.php
  services/remote-installer-skin.php
Labels: In Progress

#3586 Cleanup process
  assets/css/builder.css.map
  assets/css/dashboard.min.css
  assets/css/dashboard.min.css.map
  assets/css/display-opinions-dark.css.map
  assets/css/display-opinions-light.css.map
  assets/css/display-opinions.css.map
  assets/css/display-structure.css.map
  assets/js/min/dashboard.min.js
  assets/js/min/dashboard.min.js.map
  assets/scss/dashboard/dashboard.scss
  client/dashboard/views/dashboardView.js
  includes/AJAX/REST/BatchProcess.php
  includes/Admin/Menus/Forms.php
  includes/Admin/Notices.php
  includes/Admin/Processes/DataCleanup.php
  includes/Config/i18nDashboard.php
  ninja-forms.php
Labels: Needs Review

#3580 Added early escape for any fields that have somehow gotten corrupted
  includes/Admin/Menus/Submissions.php
Labels: In Progress, Needs Review

#3590 Updated styles for the new Store Submissions Action options.
  assets/css/builder.css
  assets/css/builder.css.map
  assets/js/builder/views/app/drawer/optionRepeaterOption.js
  assets/js/min/builder.js
  assets/js/min/builder.js.map
  assets/js/min/dashboard.min.js
  assets/js/min/dashboard.min.js.map
  assets/scss/admin/drawer-settings.scss
  client/dashboard/views/dashboardView.js
  includes/Templates/admin-menu-new-form.html.php
Labels: In Progress, Needs Review

#3588 Delete All Data Changes
  includes/AJAX/Controllers/DeleteAllData.php
  includes/Admin/Menus/Settings.php
  includes/Database/Migrations.php
Labels: Needs Review

#3595 Added check to set our data as clean if this is a brand new installation of Ninja Forms.
  ninja-forms.php
Labels: Needs Review
