Repository wpninjas/ninja-forms, pull requests merged in 2018-04, with the labels that each got.

#3465 Modified DOM constructor to used proper selection attribute.
  assets/js/builder/views/app/drawer/optionRepeaterOption.js
  assets/js/min/builder.js
  assets/js/min/builder.js.map
Labels: Needs Review

#3458 Dispatch forms
  assets/js/min/dashboard.min.js
  assets/js/min/dashboard.min.js.map
  client/dashboard/views/dashboardView.js
  includes/AJAX/Controllers/DispatchPoints.php
  includes/Admin/Menus/Forms.php
  includes/Dispatcher.php
Labels: Needs Review

#3483 Updated regex pattern to allow for spaces in list field values.
  assets/js/builder/controllers/fields/fieldList.js
  assets/js/min/builder.js
  assets/js/min/builder.js.map
Labels: In Progress, Needs Review

#3486 Added strings to the options for the save table selector.
  assets/js/builder/views/app/drawer/optionRepeaterOption.js
  assets/js/min/builder.js
  assets/js/min/builder.js.map
  assets/js/min/front-end--datepicker.min.js
  assets/js/min/front-end--rte.min.js
Labels: Needs Review

#3496 Removing Margin from hidden field labels
  assets/css/display-opinions-dark.css
  assets/css/display-opinions-dark.css.map
  assets/css/display-opinions-light.css
  assets/css/display-opinions-light.css.map
  assets/css/display-structure.css
  assets/css/display-structure.css.map
  assets/js/min/front-end--datepicker.min.js
  assets/js/min/front-end--rte.min.js
  assets/scss/front-end/st-label-positions.scss
Labels: In Progress

#3493 List labels will be returned on the front end instead of the list value
  includes/MergeTags/Fields.php
Labels: Needs Review

#3511 Added isset check to avoid throwing PHP warning in 5.2.
  includes/Libraries/Whip/NF_Whip.php
Labels: In Progress, Needs Review

#3509 Correct busted field keys at generation.
  assets/js/builder/controllers/fields/key.js
  assets/js/lib/backbone.marionette3.min.js
  assets/js/min/builder.js
  assets/js/min/builder.js.map
  assets/js/min/front-end--datepicker.min.js
  assets/js/min/front-end--rte.min.js
Labels: Needs Review

#3501 Clear out unneeded sourcemaps
  assets/js/min/builder.js
  assets/js/min/builder.js.map
  assets/js/min/dashboard.min.js
  assets/js/min/dashboard.min.js.map
  assets/js/min/front-end.js
  assets/js/min/front-end.js.map
  gulpfile.js
Labels: In Progress
